version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clientes
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cliente
    ports:
      - "8000:8000"
    depends_on:
      - db