version: '3'

services:
  nginx:
    image: nginx:latest
    ports: 
      - "8000:8000"
    volumes:
      - .:/cliente
      - ./config:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clientes
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
  migration:
    build: .
    command: python3 manage.py migrate --noinput
    volumes:
      - .:/cliente
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cliente
    expose:
      - "8000"
    depends_on:
      - migration
      - db